- name: debian | Install munge packages
  apt: name={{item}} state=installed
  with_items:
    - munge
- name: Fixup munge commandline parameters
  copy: src=munge.service dest=/etc/systemd/system/munge.service.d/override.conf 
- name: Restart systemd
  command: systemctl daemon-reload
- name: Generate a new munge key
  command: create-munge-key -f
  run_once: true
- name: Start munge service
  service: name=munge state=started enabled=yes
- name: debian | Install slurm packages
  apt: name={{item}} state=installed
  with_items:
    - slurm-wlm
    - slurm-wlm-basic-plugins
    - sview

- name: debian | Install slurmdbd packages
  apt: name={{item}} state=installed
  with_items:
    - slurmdbd
