- name: Install slurm config file
  copy: src=/zdata/slurm.conf dest={{slurm_conf_dir}}/slurm.conf owner=root group=root mode=0644 remote_src=True
#- name: Apply firewall rules
#  firewalld: port=6818 permanent=true state=enabled
- name: Start slurm node service
  service: name={{slurmd_service_name}} state=started enabled=yes

- name: Inform master of our node
  command: scontrol update NodeName={{slurm_nodename}} NodeAddr={{ansible_eth0.ipv4.address}} NodeHostName={{slurm_nodename}}
